

(dribble-on "rulebase.log")
(batch* "bin\\dr-device.bat")
(set-verbose on)
(set-debug off)
(set-time-report off)
(set-compact-proofs on)
(set-export-non-proved off)
; Bypass Java/Saxon XSLT pipeline - load pre-generated .clp directly
; rulebase.clp is generated by transform_lrml.py (Python XSLT replacement)
(load-dr-device "rulebase.clp")
(dribble-off)
(exit)
(exit)